name: Basic CI  # ✅ This is the name that must appear as the status check!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run a dummy check
        run: echo "✅ CI passed!"
